name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  linux-arm:
    runs-on: ubuntu-24.04-arm
    steps:
    - run: uname -m
  linux-x86:
    runs-on: ubuntu-latest
    steps:
    - run: apt search sdl3
    
   
